// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mshznyimtxhuiwyslaap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zaHpueWltdHhodWl3eXNsYWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDk1MDYsImV4cCI6MjA2OTc4NTUwNn0.Y4a-eWlStM76LHVNvyTe-Pw0VjrsgYx-TvworkkrtJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});